# Copies the shared data from the Android app (../akl-live-android) into this
# app as plain JS: the post-CRL network schematic, the 27H's stops and the
# fleet list. Re-run after regenerating or editing them there.
#
#   python tools/import_android.py
import json, os, re

HERE = os.path.dirname(os.path.abspath(__file__))
ANDROID = os.path.normpath(os.path.join(HERE, "..", "..", "akl-live-android"))
DATA = os.path.join(ANDROID, "app", "src", "main", "java", "nz", "aryan", "akllive", "data")
ASSETS = os.path.join(ANDROID, "app", "src", "main", "assets")
OUT = os.path.join(HERE, "..", "src", "js", "data")

NUM = r"-?\d+(?:\.\d+)?"


def floats(s):
    return [float(v) for v in s.split(",") if v.strip()]


def block(src, name):
    """The text of `val NAME ... = listOf(...)` up to its closing paren."""
    i = src.index("val " + name)
    depth, j = 0, src.index("(", i)
    for k in range(j, len(src)):
        if src[k] == "(":
            depth += 1
        elif src[k] == ")":
            depth -= 1
            if depth == 0:
                return src[j:k + 1]
    raise ValueError(name)


def network():
    src = open(os.path.join(DATA, "MapData.kt"), encoding="utf-8").read()
    f_list = lambda name: [floats(m) for m in re.findall(r'f\("([^"]*)"\)', block(src, name))]
    one = lambda name: floats(re.search(r"val " + name + r'\s*=\s*f\("([^"]*)"\)', src).group(1))
    net = {
        "w": float(re.search(r"const val W = (" + NUM + ")f", src).group(1)),
        "h": float(re.search(r"const val H = (" + NUM + ")f", src).group(1)),
        "lineIds": re.findall(r'"([^"]+)"', re.search(r"LINE_IDS = arrayOf\(([^)]*)\)", src).group(1)),
        "lineNames": re.findall(r'"([^"]+)"', re.search(r"LINE_NAMES = arrayOf\(([^)]*)\)", src).group(1)),
        # AT's own line colours: route_color for E-W-201, S-C-201 and O-W-201 in its GTFS
        "lineColors": ["#97C93D", "#D52923", "#00AEEF"],
        "lineDraw": f_list("LINE_DRAW"),
        "crlLoop": one("CRL_LOOP"),
        "land": f_list("LAND"),
        "landRound": [float(v) for v in re.findall(NUM, re.search(r"LAND_ROUND = floatArrayOf\(([^)]*)\)", src).group(1))],
        "water": f_list("WATER"),
        "cones": one("CONES"),
        "stations": [],
        "segs": [],
    }
    st = re.compile(r'Station\("([^"]*)", "([^"]*)", f\("([^"]*)"\), (' + NUM + r"), (" + NUM + r"), (\d+), '(\w)', ("
                    + NUM + r")f, (" + NUM + r')f, (\d+), (true|false), "([^"]*)"\)')
    for m in st.finditer(src):
        key, name, pts, lat, lon, lines, anchor, dx, dy, prio, crl, plats = m.groups()
        net["stations"].append({
            "key": key, "name": name, "pts": floats(pts), "lat": float(lat), "lon": float(lon),
            "lines": int(lines), "anchor": anchor, "dx": float(dx), "dy": float(dy),
            "priority": int(prio), "crl": crl == "true",
            "platforms": dict(p.split("=", 1) for p in plats.split(";") if p),
        })
    sg = re.compile(r'Seg\((\d+), (\d+), (\d+), f\("([^"]*)"\), (' + NUM + r"), (" + NUM + r"), (" + NUM + r"), (" + NUM + r")\)")
    for m in sg.finditer(src):
        line, a, b, poly, la0, lo0, la1, lo1 = m.groups()
        net["segs"].append({"line": int(line), "from": int(a), "to": int(b), "poly": floats(poly),
                            "lat0": float(la0), "lon0": float(lo0), "lat1": float(la1), "lon1": float(lo1)})
    assert len(net["stations"]) > 40 and len(net["segs"]) > 60, "MapData.kt format changed"
    return net


def routes():
    src = open(os.path.join(DATA, "RouteData.kt"), encoding="utf-8").read()
    out = {}
    for code, label, body in re.findall(r'"(\d+)" to \("([^"]*)" to parse\("([^"]*)"\)\)', src):
        stops = []
        for row in body.split("\\n"):
            c, n, la, lo = row.split("|")
            stops.append({"code": c, "name": n, "lat": float(la), "lon": float(lo)})
        out[code] = {"label": label, "stops": stops}
    assert out, "RouteData.kt format changed"
    return out


def fleet():
    models = json.load(open(os.path.join(ASSETS, "models.json"), encoding="utf-8"))
    ranges = []
    for line in open(os.path.join(ASSETS, "fleet.tsv"), encoding="utf-8"):
        line = line.rstrip("\n")
        if not line or line.startswith("#"):
            continue
        p = line.split("\t")
        ranges.append([p[0], int(p[1]), int(p[2]), p[3].strip()])
    return {"models": models, "ranges": ranges}


def write(name, var, obj):
    os.makedirs(OUT, exist_ok=True)
    path = os.path.join(OUT, name)
    with open(path, "w", encoding="utf-8", newline="\n") as fh:
        fh.write("// Generated by tools/import_android.py from ../akl-live-android. Don't edit by hand.\n")
        fh.write("window.AKL = window.AKL || {};\n")
        fh.write("AKL.%s = %s;\n" % (var, json.dumps(obj, ensure_ascii=False, separators=(",", ":"))))
    print("wrote", os.path.relpath(path), os.path.getsize(path), "bytes")


if __name__ == "__main__":
    write("network.js", "NET", network())
    write("routes.js", "ROUTES", routes())
    write("fleet.js", "FLEET_DATA", fleet())
